---
- name: install Remi
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: install PHP
  yum:
    enablerepo: "remi,remi-php80"
    name:
      - php
      - php-common
      - php-cli
      - php-gd
      - php-curl
      - php-mysqlnd
      - php-fpm
      - php-mysqli
      - php-json
      - php-mbstring
      - php80-php-pdo
      - php-xml
    state: present

